USE [master]
GO

/****** Object:  Database [PROJETO_ENTREVISTA]    Script Date: 30/06/2020 15:54:06 ******/
CREATE DATABASE [PROJETO_ENTREVISTA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PROJETO_ENTREVISTA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PROJETO_ENTREVISTA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PROJETO_ENTREVISTA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PROJETO_ENTREVISTA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PROJETO_ENTREVISTA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET ARITHABORT OFF 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET  MULTI_USER 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PROJETO_ENTREVISTA] SET  READ_WRITE 
GO


